source("https://raw.githubusercontent.com/icascos/intervaldepth/master/interval_depth.R")

# several bivariate region depths w.r.t. a sample of 200 observations of a normal distribution

set.seed(123)
par(mfrow=c(2,2))
gaussian <- mvrnorm(n=200,mu=c(0,0),Sigma=matrix(c(1,.6,.6,1),nrow=2))
gaussian1 <- mvrnorm(n=40,mu=c(0,0),Sigma=matrix(c(1,.6,.6,1),nrow=2))
plot(NA,xlim=c(-4,4),ylim=c(-4,4),axes=F,xlab="",ylab="")
points(gaussian,pch=16,cex=0.3,col="honeydew4")
lines(zonoidreg(gaussian),lwd=2,col="honeydew4")
points(gaussian1,pch=16,cex=0.3)
lines(zonoidreg(gaussian1),lwd=2)
title(main="Same distribution",xlab=paste("depth=",round(m1m2depthr2(gaussian1,gaussian),3),sep=""))

gaussian2 <- mvrnorm(n=40,mu=c(0,0),Sigma=matrix(c(1,-.6,-.6,1),nrow=2))
plot(NA,xlim=c(-4,4),ylim=c(-4,4),axes=F,xlab="",ylab="")
points(gaussian,pch=16,cex=0.3,col="honeydew4")
lines(zonoidreg(gaussian),lwd=2,col="honeydew4")
points(gaussian2,pch=16,cex=0.3)
lines(zonoidreg(gaussian2),lwd=2)
title(main="Shift in correlation",xlab=paste("depth=",round(m1m2depthr2(gaussian2,gaussian),3),sep=""))

gaussian3 <- mvrnorm(n=40,mu=c(.5,.5),Sigma=matrix(c(1,.6,.6,1),nrow=2))
plot(NA,xlim=c(-4,4),ylim=c(-4,4),axes=F,xlab="",ylab="")
points(gaussian,pch=16,cex=0.3,col="honeydew4")
lines(zonoidreg(gaussian),lwd=2,col="honeydew4")
points(gaussian3,pch=16,cex=0.3)
lines(zonoidreg(gaussian3),lwd=2)
title(main="Shift in location",xlab=paste("depth=",round(m1m2depthr2(gaussian3,gaussian),3),sep=""))

gaussian4 <- mvrnorm(n=40,mu=c(0,0),Sigma=matrix(2*c(1,.6,.6,1),nrow=2))
plot(NA,xlim=c(-4,4),ylim=c(-4,4),axes=F,xlab="",ylab="")
points(gaussian,pch=16,cex=0.3,col="honeydew4")
lines(zonoidreg(gaussian),lwd=2,col="honeydew4")
points(gaussian4,pch=16,cex=0.3)
lines(zonoidreg(gaussian4),lwd=2)
title(main="Shift in scale",xlab=paste("depth=",round(m1m2depthr2(gaussian4,gaussian),3),sep=""))
